### ISSUE TITLE
Bug with connect button

### ISSUE THREAD

**Issue by yoloplayerr** [amnezia-vpn/amnezia-client#254]
fix the bug with connecting button click on iOS

**Comment by maximvarentsov** [comment]
Confirm, iOS 16.6 connect button not work, will be fixed?

**Comment by pokamest** [comment]
Fixed in latest release 3.1.0

**Comment by d3nbr0** [comment]
Not fixed yet(
The connection button resets its state immediately after pressing

iOS: 17.3.1
App Version: 4.4.1

**Comment by pokamest** [comment]
@d3nbr0 could you please contact us in the Telegram, we need to get more info and solve this issue.
