### ISSUE TITLE
[BUG] AWG config parsing on iOS

### ISSUE THREAD

**Issue by danpashin** [amnezia-vpn/amnezia-client#680]
**Describe the bug**
~~This error comes from #577. The thing is `wgConfigData` variable in `-[PacketTunnelProvider startWireguard]` lacks client_pub_key json value. I don't know yet in what situations this happens but struct decoding fails because of this error. This leads to app being visually connected but it's not.~~

That was between that PR and dev branch. Now `wgConfig` struct in `-[PacketTunnelProvider startWireguard]` has `allowedIPs` field set to an empty string for some reason. This leads to the same behaviour - app being visually connected but it's not.

I'll see a bit later how exactly this can be fixed.

**To Reproduce**
Import AWG config and connect. App will show "Connected" state as well as system will show "VPN" badge but it won't be really connected.

**Expected behavior**
App mustn't pass any invalid json in this part

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - Version: 16.6.1

**Comment by danpashin** [comment]
Seems like that's invalid in dev branch now...

**Comment by danpashin** [comment]
Reopening as I've investigated some more and found `allowedIPs` struct field now contains empty string
<img width="247" alt="Screenshot 2024-03-11 at 21 31 31" src="https://github.com/amnezia-vpn/amnezia-client/assets/11134266/102c6cf6-91c0-47e0-a9fe-f4446e4d7692">

**Comment by danpashin** [comment]
Fixed by #686

**Comment by vgrebenschikov** [comment]
Still have problems on v4.4.1 and v4.4.2 on iOS - tunnel shown as "Connected" but actually packets did not sent to tunnel interface

while returning back to v4.4.0 fixes the problem

**Comment by pokamest** [comment]
@vgrebenschikov we will upload new release to TestFlight soon
